### PR TITLE
changes in navbar

### PR DESCRIPTION
**Pull request by stephosj07**
Moved navbar.html.erb in a shared folder and added line to connect in application.html.erb.
Added links in navbar to sign up, log in , and log out

### CODE REVIEW

**Review by aleezuck — COMMENTED** [review]
we can add some logic depending if the user is logged in or not

**Comment by stephosj07** [comment]
I will work on that right away and let youy know when it is done!

**Comment by stephosj07** [comment]
Just pushed again

**Review by aleezuck — APPROVED** [review]
looks good :)

**Pull request merged**
